config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  # Add and remove products from the session cart.
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  post 'products/change_quantity/:id', to: 'products#change_quantity', as: 'change_quantity'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  get "/cart", to: "static_pages#cart"

  # Routes for the order process.
  get 'orders/customer_information', to: 'orders#customer_information', as: 'customer_information'
  get 'orders/invoice', to: 'orders#invoice', as: 'invoice'
  get 'orders/payment_information', to: 'orders#payment_information', as: 'payment_information'
  post 'orders/create_order', to: 'orders#create_order', as: 'create_order'

  resources :products, only: ['index', 'show'] do
    collection do
      get 'search'
    end
  end

  resources :categories, only: ['show']
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  has_many :products, through: :order_items

  def self.ransackable_associations(auth_object = nil)
    ["customer", "order_items", "products"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "customer_id", "id", "id_value", "total_price", "updated_at"]
  end

  validates :total_price, presence: true, numericality: { greater_than_or_equal_to: 0.01 }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!

  # This does absolutely nothing with the payment info.
  # There is no payment processing, just order creation.
  def create_order
    # Find customer
    customer = Customer.find(current_customer[:id])
    session[:order_message]

    pst = customer.province.pst
    gst = customer.province.gst
    hst = customer.province.hst

    total_price = 0

    # Create order through the customer using the minimum price that'll pass
    # validations. It will be changed when all the products have been summed.
    order = customer.orders.create!(total_price: 0.01)

    # Create order_items using product on cart and assign order id from previous create, add tax rates through the customer
    session[:cart].each do |item|
      product = Product.find(item[0])
      subtotal = BigDecimal(product.price - product.price * product.sale_percentage, 2) * BigDecimal(item[1], 2)

      ordered_item = product.order_items.create!(order_id: order.id,
                                                 product_id: product.id,
                                                 name: product.name,
                                                 price: subtotal,
                                                 quantity: item[1],
                                                 pst: pst,
                                                 gst: gst,
                                                 hst: hst)

      total_price += subtotal
    end

    total_price = BigDecimal(total_price, 2) + BigDecimal(total_price * pst, 2) + BigDecimal(total_price * gst, 2) + BigDecimal(total_price * hst, 2)

    order.total_price = total_price
    order.save!

    # delete cart
    session[:cart] = []

    # redirect
    redirect_to root_path, notice: "Order processed successfully!"
  end

  def invoice
  end

  def payment_information
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/customer_information.html.erb
<section class="section px-6">
  <div class="grid">
    <div class="cell is-col-span-8 card p-0">
      <header class="card-header py-5">
        <h2 class="card-header-title title is-3">Address Details</h2>
      </header>
      <div class="card-content px-5">
        <div class="grid">
          <div class="cell">
            <p>Name: <%= current_customer[:name] %></p>
          </div>

          <div class="cell">
            <p>Email: <%= current_customer[:email] %></p>
          </div>

          <div class="cell">
            <p>Address: <%= current_customer[:address] %></p>
          </div>

          <div class="cell">
            <p>Province: <%= Province.find(current_customer[:province_id]).name %></p>
          </div>
        </div>
      </div>

      <footer class="card-footer p-5">
        <div class="card-footer-item">
          <%= link_to 'Edit Details', edit_customer_registration_path %>
        </div>
        <div class="card-footer-item">
          <%= link_to 'Continue', invoice_path %>
        </div>
      </footer>
    </div>
  </div>
</section>

app/views/orders/invoice.html.erb
<%= render 'static_pages/items_in_cart', title: "Your Order" %>

app/views/orders/payment_information.html.erb
<section class="section px-6">
  <div class="grid">
    <div class="cell is-col-span-8 card p-0">
      <header class="card-header py-5">
        <h2 class="card-header-title title is-3">Enter Payment</h2>
      </header>
      <div class="card-content px-5">
        <%= form_with url: create_order_path, data: { turbo_method: :post } do |form| %>
          <div class="fixed-grid has-1-cols">
            <div class="grid">
              <%= form.label :credit_name, "Name on Card:" %>
              <%= form.text_field :credit_name, class: "input" %>

              <%= form.label :payment, "Enter Credit Card Number:" %>
              <%= form.number_field :payment, class: "input" %>


              <%= form.label :cvc, "Enter 3 Digit Code:" %>
              <%= form.number_field :cvc, class: "input" %>

              <%= form.label :expiry, "Expiry Date" %>
              <%= form.datetime_local_field :expiry, class: "input" %>


            </div>
          </div>

          <%= form.submit "Finish Order", class: "my-5  button is-link" %>
        <% end %>
      </div>
    </div>
  </div>
</section>