config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  # Add and remove products from the session cart.
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  post 'products/change_quantity/:id', to: 'products#change_quantity', as: 'change_quantity'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  get "/cart", to: "static_pages#cart"

  # Routes for the order process.
  get 'orders/customer_information', to: 'orders#customer_information', as: 'customer_information'
  get 'orders/invoice', to: 'orders#invoice', as: 'invoice'
  get 'orders/payment_information', to: 'orders#payment_information', as: 'payment_information'
  post 'orders/create_order', to: 'orders#create_order', as: 'create_order'

  resources :products, only: ['index', 'show'] do
    collection do
      get 'search'
    end
  end

  resources :categories, only: ['show']
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :admin_display, resize_to_limit: [100, 200], quality: 100
    attachable.variant :small_display, resize_and_pad: [400, 400, background: [255, 255, 255]], quality: 100
  end

  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories, :image_attachment, :image_blob, allow_destroy: true
  has_many :order_items
  has_many :orders, through: :order_items

  # Define the attributes and associations that active admin can search.
  def self.ransackable_attributes(auth_object = nil)
    ["image_record_id", "image_blob_id", "description", "id", "id_value", "name", "on_sale", "sale_percentage", "price", "stock_quantity", "created_at", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob", "categories", "order_items", "orders"]
  end

  validates :name, uniqueness: true
  validates :name, :description, presence: true, length: { minimum: 2 }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :stock_quantity, numericality: { only_integer: true, greater_than: 0 }
  validates :on_sale, inclusion: [true, false]
  validates :sale_percentage, presence: true, numericality: { in: 0..1 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
  end

  # Allow for searching for products via keyword with
  # option to narrow search down by category.
  def search
    # Get the keyword from the search form input.
    @query = params[:q]

    if @query.strip == ""
      redirect_to root_path
    elsif params[:category_filter].blank?
      # Search for keyword in Product names or descriptions.
      @products = Product.where('name LIKE ?', "%#{@query}%").or(Product.where('description LIKE ?', "%#{@query}%")).page(params[:page])

      # Count all of the products found.
      @count = @products.total_count
    else
      @category_filter = params[:category_filter]

      # Search products with a category filter.
      @products = Product.where('products.name LIKE ?', "%#{@query}%").or(Product.where('products.description LIKE ?', "%#{@query}%")).includes(:categories).where('categories.name = ?', @category_filter).references(:categories).page(params[:page])

      # Count all of the products found.
      @count = @products.total_count
    end
  end

  def change_quantity
    id = params[:id].to_i
    quantity = params[:quantity].to_i

    if quantity >= 1
      # Find and return the whole array that contains the id.
      find_array = session[:cart].find { |el| el[0] == id}

      # Then search for the index of that array in the cart.
      array_index = session[:cart].find_index(find_array)

      session[:cart][array_index][1] = quantity
    end

    redirect_to cart_path
  end

  def add_to_cart
    # Get the id param from the link and set the quantity to one by default.
    id = params[:id].to_i
    quantity = 1

    session[:cart] << [id, quantity] unless session[:cart].find { |el| el[0] == id}
    redirect_to root_path
  end

  def remove_from_cart
    id = params[:id].to_i
    # Find the index of the array that contains the specified id.
    delete_array = session[:cart].find { |el| el[0] == id}

    session[:cart].delete(delete_array)
    redirect_to root_path
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_display_products.html.erb
<div class="cell is-col-span-12 is-flex"><%= paginate products %></div>

<div class="cell is-col-span-7 ml-6">
  <div class="fixed-grid has-1-cols-mobile has-3-cols">
    <div class="grid is-gap-0">
      <% products.each do |product| %>
        <div class="cell is-row-span-1 card is-shadowless is-radiusless m-0">
          <div class="card-image p-5">
            <figure class="image">
              <%= image_tag product.image.variant(:small_display), alt: product.name %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media-content">
              <p class="title is-4"><%= link_to product.name, product %></p>
              <% if product.on_sale %>
                <h2 class="subtitle is-6 has-text-success"><%= number_to_currency (BigDecimal(product.price - product.price * product.sale_percentage, 2)) %></h2>
                <p class="subtitle is-6 has-text-grey">Usually $<%= product.price %></p>
              <% else %>
                <h2 class="subtitle is-6">$<%= product.price %></h2>
              <% end %>
              <% if @cart.find { |el| el[:product][:id] == product.id} %>
                <p>Product in cart | <%= link_to 'Remove from cart', remove_from_cart_path(product.id), data: { turbo_method: :delete } %></p>
              <% else %>
                <%= link_to 'add to cart', add_to_cart_path(product.id), data: { turbo_method: :post } %>
              <% end %>
            </div>
            <% if current_page?(controller: 'products', action: 'search') %>
              <div class="content">
                <%= product.description %>
              </div>
              <footer class="card-footer">
                <% product.categories.each do |category| %>
                  <p class="card-footer-item">
                    <span>
                      <%= category.name %>
                    </span>
                  </p>
                <% end %>
              </footer>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_footer_display.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p class="subtitle">API Data from <a href="https://api.nookipedia.com/doc">Nookipedia</a> was granted to me to create this project.</p>
    <p class="subtitle">All photos belong to the game Animal Crossing New Horizon, and were collected from the API.</p>
  </div>
</footer>

app/views/products/_header_nav.html.erb
<nav class="navbar p-5" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div class="navbar-menu" id="navMenu" >
    <div class="navbar-start">
      <div class="navbar-item">
        <%= link_to "Home", root_path %>
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <% if customer_signed_in? %>
          <div class="buttons">
            <%= link_to 'My Account', edit_customer_registration_path %>
            <%= link_to 'Log out', destroy_customer_session_path, data: { turbo_method: :delete } %>
          </div>
        <% else %>
          <div class="buttons">
            <%= link_to 'Sign up', new_customer_registration_path %>
            <%= link_to 'Sign in', customer_session_path %>
          </div>
        <% end %>
      </div>
      <div class="navbar-item">
        <%= link_to "Cart", cart_path %>
      </div>
    </div>
  </div>
</nav>

app/views/products/_side_menu.html.erb
<div class="cell is-col-span-4 is-col-start-9 px-6">
  <aside class="menu">
    <p class="menu-label">Search</p>
      <%= form_with(url: search_products_path, method: "get") do |form| %>
        <div class="field has-addons">
          <div class="control">
            <%= form.label :q, "Search products:", class: "is-sr-only" %>
          </div>
          <div class="control is-expanded">
            <%= form.text_field :q, class:"input is-small is-fullwidth" %>
          </div>
          <div class="control is-expanded">
            <%= form.collection_select :category_filter, Category.order(:name), :name, :name, { :include_blank => "Any" }, class: "select is-small is-fullwidth" %>
          </div>
          <div class="control">
            <%= form.submit "Search", class:"button is-small is-info" %>
          </div>
        </div>
      <% end %>
    <p class="menu-label">Categories</p>
    <ul class="menu-list">
      <% Category.all.each do |category| %>
        <li><%= link_to category.name, category %></li>
      <% end %>
    </ul>
  </aside>
</div>

app/views/products/index.html.erb
<section class="section">
  <div class="grid mx-6">
    <div class="cell is-col-span-12">
      <div class="grid">
        <div class="cell">
          <h1 class="title is-1">Forest Critter Crafting</h1>

          <h2 class="subtitle is-5">Made with love and immense amounts of detail</h2>
        </div>
      </div>
    </div>

    <%= render "display_products", products: @products %>

    <%= render "side_menu" %>
  </div>
</section>

app/views/products/search.html.erb
<section class="section">
  <div class="grid">
    <div class="cell is-col-span-12">
      <h1 class="subtitle is-5">Search: <%= @query %></h1>
      <p>Showing <%= pluralize(@count, 'result') %> </p>
    </div>

    <%= render "display_products", products: @products %>

    <%= render "products/side_menu" %>
  </div>
</section>

app/views/products/show.html.erb
<section class="section">
  <div class="fixed-grid has-2-cols">
    <div class="grid box m-6 px-0">
      <div class="cell">
        <figure class="image px-6">
          <%= image_tag @product.image.variant(:small_display), alt: @product.name %>
        </figure>
      </div>

      <div class="cell">
        <div class="grid is-col-min-12">
          <div class="cell is-col-span-12">
            <h1 class="title mt-5 mb-4 is-2 has-text-centered"><%= @product.name %></h1>

            <% if @product.on_sale %>
              <h2 class="subtitle is-4 has-text-success has-text-centered"><%= number_to_currency (BigDecimal(@product.price - @product.price * @product.sale_percentage, 2)) %></h2>
              <p class="subtitle is-6 has-text-grey-dark has-text-centered">Usually $<%= @product.price %></p>
            <% else %>
              <h2 class="subtitle mb-5 is-4 has-text-centered">$<%= @product.price %></h2>
            <% end %>
          </div>
          <div class="cell is-col-span-12 hero is-primary">
            <div class="hero-body">
              <p class="title mb-4">In-Game Description:</p>
              <p class="subtitle"><%= @product.description %></p>
            </div>
          </div>
          <div class="cell is-col-span-12 p-4">
            <p class="has-text-centered">We have <%= @product.stock_quantity %> in stock currently. If you want to order more, contact us <a href="#">here</a>.</p>
          </div>
          <div class="cell is-col-span-12 p-4">
            <% if @cart.find { |el| el[:product][:id] == @product.id} %>
              <p class="has-text-centered">Product in cart | <%= link_to 'Remove from cart', remove_from_cart_path(@product.id), data: { turbo_method: :delete } %></p>
            <% else %>
              <p class="has-text-centered"><%= link_to 'add to cart', add_to_cart_path(@product.id), data: { turbo_method: :post } %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>